parameters:
  ChannelId: 0

jobs:
- job: trigger_subscriptions
  displayName: Trigger subscriptions
  pool:
      vmImage: 'windows-2019'
  variables:
    - template: ../common-variables.yml
    - group: Publish-Build-Assets
    - name: IsStableBuild
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.IsStableBuild'] ]
  dependsOn: IS_Publish
  condition: eq(variables['IsStableBuild'], 'true')
  steps:
    - powershell: $(Build.SourcesDirectory)/eng/common/post-build/trigger-subscriptions.ps1
       -SourceRepo $(Build.Repository.Uri)
       -ChannelId ${{ parameters.ChannelId }}
       -BarToken $(MaestroAccessToken)
      displayName: Triggering subscriptions
