stages:
- stage: trigger_subscriptions
  variables:
    - template: ../common-variables.yml
    - group: Publish-Build-Assets
    - name: IsStableBuild
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.IsStableBuild'] ]
  dependsOn: IS_Publish
  condition: eq(variables['IsStableBuild'], 'true')
  displayName: Trigger Subscriptions
  jobs:
  - job:
    displayName: Signing Validation
      pool:
        vmImage: 'windows-2019'
      steps:
        - powershell: $(Build.SourcesDirectory)/eng/common/post-build/trigger-subscriptions.ps1
            -SourceRepo $(Build.Repository.Uri)
            -BarToken $(MaestroAccessToken)
        displayName: Publish Blobs to AzDO Feed
